// Demo listings shown only when the marketplace is empty (e.g. before
// real users have posted anything). They are clearly tagged so we can
// hide the booking action and avoid confusing test data with production.
import type { Listing } from "@/pages/Matches";

export const DEMO_LISTINGS: Listing[] = [
  {
    id: "demo-1",
    user_id: "demo-user-1",
    title: "1-on-1 Math Tutoring (Grade 8–12)",
    description: "BC-curriculum tutor. Algebra, calculus, and exam prep. Patient and structured.",
    category: "Tutoring",
    point_price: 45,
    delivery_type: "both",
    service_radius_km: 15,
    city_id: null,
    city_name: "Vancouver",
    province: "BC",
    display_name: "Sarah Chen",
    avatar_url: null,
    trust_score: 96,
    rank_bucket: 1,
    distance_km: null,
    rating: 4.9,
    review_count: 38,
  },
  {
    id: "demo-2",
    user_id: "demo-user-2",
    title: "Logo & Brand Identity Design",
    description: "Boutique logos, colour palettes, typography. 2 concepts, 3 revisions included.",
    category: "Graphic Design",
    point_price: 80,
    delivery_type: "online",
    service_radius_km: 0,
    city_id: null,
    city_name: "Burnaby",
    province: "BC",
    display_name: "Marcus Rivera",
    avatar_url: null,
    trust_score: 92,
    rank_bucket: 3,
    distance_km: null,
    rating: 4.8,
    review_count: 24,
  },
  {
    id: "demo-3",
    user_id: "demo-user-3",
    title: "Resume + LinkedIn Refresh",
    description: "ATS-optimized resume rewrite plus a polished LinkedIn headline & about section.",
    category: "Resume Help",
    point_price: 35,
    delivery_type: "online",
    service_radius_km: 0,
    city_id: null,
    city_name: "Victoria",
    province: "BC",
    display_name: "Priya Sharma",
    avatar_url: null,
    trust_score: 89,
    rank_bucket: 3,
    distance_km: null,
    rating: 4.7,
    review_count: 51,
  },
  {
    id: "demo-4",
    user_id: "demo-user-4",
    title: "Personal Fitness Coaching",
    description: "Custom 4-week program + weekly check-ins. Strength, mobility, or fat loss focus.",
    category: "Fitness Coaching",
    point_price: 55,
    delivery_type: "in_person",
    service_radius_km: 20,
    city_id: null,
    city_name: "Surrey",
    province: "BC",
    display_name: "Jordan MacLeod",
    avatar_url: null,
    trust_score: 94,
    rank_bucket: 2,
    distance_km: 8.4,
    rating: 5.0,
    review_count: 19,
  },
  {
    id: "demo-5",
    user_id: "demo-user-5",
    title: "Beginner Spanish Lessons",
    description: "Conversational Spanish for travel & work. Native speaker, 10+ years teaching.",
    category: "Language Lessons",
    point_price: 40,
    delivery_type: "both",
    service_radius_km: 10,
    city_id: null,
    city_name: "Kelowna",
    province: "BC",
    display_name: "Elena Vasquez",
    avatar_url: null,
    trust_score: 91,
    rank_bucket: 1,
    distance_km: null,
    rating: 4.9,
    review_count: 27,
  },
  {
    id: "demo-6",
    user_id: "demo-user-6",
    title: "Web App MVP Coaching",
    description: "Senior dev. React/TypeScript code reviews and architecture guidance.",
    category: "Coding",
    point_price: 110,
    delivery_type: "online",
    service_radius_km: 0,
    city_id: null,
    city_name: "Richmond",
    province: "BC",
    display_name: "Devon Park",
    avatar_url: null,
    trust_score: 98,
    rank_bucket: 3,
    distance_km: null,
    rating: 5.0,
    review_count: 12,
  },
];
